#!/bin/sh
set -e

VENV=/opt/venvs/kraxcli
WHEEL_DIR=/opt/venvs/kraxcli/wheels

# создаём venv
python3 -m venv "$VENV"

# обновляем pip
"$VENV/bin/pip" install --upgrade pip

# ставим wheel
"$VENV/bin/pip" install "$WHEEL_DIR"/*.whl

exit 0
